In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
import lxml.html
import numpy as np
from urllib.request import urlopen as ureq
import re

In [2]:
url='https://www.pro-football-reference.com/boxscores/202011290nwe.htm'

In [3]:
uclient=ureq(url)
page_html=uclient.read()

In [4]:
#Converts to HTML
soup_page=soup(page_html,'html.parser')

In [5]:
soup=soup_page.find('table',{'id':'player_offense'})

In [6]:
soup.find_all('th')[-1].text

"N'Keal Harry "

In [7]:
#soup.tbody

In [8]:
#Finds the length of the columns
len(soup.find_all('tr')[1].find_all('th',{'scope':'col'}))

22

In [9]:
#Find the columns names in html 
cols=soup.find_all('tr')[1].find_all('th',{'scope':'col'})

In [10]:
# Gets the column names from the table as a text
col_names=[]

for x in range(len(cols)):
    col_names.append(cols[x].text)

In [11]:
col_names

['Player',
 'Tm',
 'Cmp',
 'Att',
 'Yds',
 'TD',
 'Int',
 'Sk',
 'Yds',
 'Lng',
 'Rate',
 'Att',
 'Yds',
 'TD',
 'Lng',
 'Tgt',
 'Rec',
 'Yds',
 'TD',
 'Lng',
 'Fmb',
 'FL']

In [12]:
#Gets the players
players=soup.tbody.find_all('th',{'data-stat':'player'})

In [13]:
#prints the names of players as a text

names=[]
for x in range(len(players)):
    names.append(players[x].text)
names.remove('Player')

names

['Kyler Murray ',
 'Kenyan Drake',
 'Chase Edmonds',
 'DeAndre Hopkins',
 'Andy Isabella',
 'Christian Kirk',
 'Dan Arnold',
 'Maxx Williams',
 'KeeSean Johnson',
 'Cam Newton',
 'Damien Harris ',
 'James White ',
 'Gunner Olszewski',
 'Jakobi Meyers',
 'Damiere Byrd ',
 "N'Keal Harry "]

In [14]:
# This is the number of rows aka players needed to convert into dataframe 
rows=len(names)

In [15]:
#Stats for the rows
stats=soup.tbody.find_all('td')

In [16]:
#Gets the all of the stats
full_stats=[]

for x in range(len(stats)):
    full_stats.append(stats[x].text)

In [17]:
#full_stats

In [18]:
#reshapes full stats variable into a shape that can be made into data table
array=np.reshape(full_stats,(rows,21))

In [19]:
# makes the dataframe
game=pd.DataFrame(array)

In [20]:
# grapbs the player column to move to the front of the data frame
game['Players']=np.array(names)

In [21]:
game

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,Players
0,ARI,23,34,170,0,1,2,10,19,67.0,...,0,15,0,0,0,0,0,0,0,Kyler Murray
1,ARI,0,0,0,0,0,0,0,0,,...,2,14,4,3,15,0,6,0,0,Kenyan Drake
2,ARI,0,0,0,0,0,0,0,0,,...,0,9,5,4,14,0,7,0,0,Chase Edmonds
3,ARI,0,0,0,0,0,0,0,0,,...,0,0,7,5,55,0,16,0,0,DeAndre Hopkins
4,ARI,0,0,0,0,0,0,0,0,,...,0,0,6,4,33,0,19,0,0,Andy Isabella
5,ARI,0,0,0,0,0,0,0,0,,...,0,0,6,3,19,0,8,0,0,Christian Kirk
6,ARI,0,0,0,0,0,0,0,0,,...,0,0,3,1,17,0,17,0,0,Dan Arnold
7,ARI,0,0,0,0,0,0,0,0,,...,0,0,2,2,10,0,6,0,0,Maxx Williams
8,ARI,0,0,0,0,0,0,0,0,,...,0,0,1,1,7,0,7,0,0,KeeSean Johnson
9,NWE,9,18,84,0,2,3,15,17,23.6,...,0,14,0,0,0,0,0,0,0,Cam Newton
10,NWE,0,0,0,0,0,0,0,0,,...,0,18,0,0,0,0,0,0,0,Damien Harris
11,NWE,0,0,0,0,0,0,0,0,,...,2,7,1,1,-1,0,-1,0,0,James White
12,NWE,0,0,0,0,0,0,0,0,,...,0,1,0,0,0,0,0,0,0,Gunner Olszewski
13,NWE,0,0,0,0,0,0,0,0,,...,0,0,6,5,52,0,17,0,0,Jakobi Meyers
14,NWE,0,0,0,0,0,0,0,0,,...,0,0,8,3,33,0,17,0,0,Damiere Byrd
15,NWE,0,0,0,0,0,0,0,0,,...,0,-2,2,0,0,0,0,0,0,N'Keal Harry

In [22]:
game.columns.values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 'Players'], dtype=object)

In [23]:
#reorders the columns so that Players is the first column
reordered=['Players',0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,19, 20]

game=game[reordered]

In [24]:
#Renames the columns based off the col_names from the loop
game.columns=col_names

game

,Player,Tm,Cmp,Att,Yds,TD,Int,Sk,Yds,Lng,...,Yds,TD,Lng,Tgt,Rec,Yds,TD,Lng,Fmb,FL
0,Kyler Murray,ARI,23,34,170,0,1,2,10,19,...,31,0,15,0,0,0,0,0,0,0
1,Kenyan Drake,ARI,0,0,0,0,0,0,0,0,...,78,2,14,4,3,15,0,6,0,0
2,Chase Edmonds,ARI,0,0,0,0,0,0,0,0,...,29,0,9,5,4,14,0,7,0,0
3,DeAndre Hopkins,ARI,0,0,0,0,0,0,0,0,...,0,0,0,7,5,55,0,16,0,0
4,Andy Isabella,ARI,0,0,0,0,0,0,0,0,...,0,0,0,6,4,33,0,19,0,0
5,Christian Kirk,ARI,0,0,0,0,0,0,0,0,...,0,0,0,6,3,19,0,8,0,0
6,Dan Arnold,ARI,0,0,0,0,0,0,0,0,...,0,0,0,3,1,17,0,17,0,0
7,Maxx Williams,ARI,0,0,0,0,0,0,0,0,...,0,0,0,2,2,10,0,6,0,0
8,KeeSean Johnson,ARI,0,0,0,0,0,0,0,0,...,0,0,0,1,1,7,0,7,0,0
9,Cam Newton,NWE,9,18,84,0,2,3,15,17,...,46,0,14,0,0,0,0,0,0,0
10,Damien Harris,NWE,0,0,0,0,0,0,0,0,...,47,0,18,0,0,0,0,0,0,0
11,James White,NWE,0,0,0,0,0,0,0,0,...,18,2,7,1,1,-1,0,-1,0,0
12,Gunner Olszewski,NWE,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
13,Jakobi Meyers,NWE,0,0,0,0,0,0,0,0,...,0,0,0,6,5,52,0,17,0,0
14,Damiere Byrd,NWE,0,0,0,0,0,0,0,0,...,0,0,0,8,3,33,0,17,0,0
15,N'Keal Harry,NWE,0,0,0,0,0,0,0,0,...,-2,0,-2,2,0,0,0,0,0,0

In [25]:
#Saves to an excel
game.to_excel('ARI_V_NWE.xlsx')